add_newline = true

[git_commit]
commit_hash_length = 4
tag_symbol = "ðŸ”– "

[directory]
truncation_length = 8

[java]
disabled = false
detect_extensions = ["java", "class", "gradle", "cljs", "cljc"]
[jobs]
disabled = false

[battery]
disabled=true
